const {
  buildSimpleForm,
  text,
  select,
  date,
  textarea,
  number,
  radio,
  checkbox,
  switchField,
  upload,
} = require('../index');

module.exports = buildSimpleForm({
  pageName: 'xxx页面',
  frontId: 'xxxFrontId',
  functionGid: '92bc6124ae5a475dad12cfd1ebc286fa',
  productGid: '181A7E84452003',
  projectGid: 'PJ181A490E5D4001',
  appGid: '181A7E84452003',
  branch: 'test',
  createBy: 'sysadmin',
  createTime: '2022-09-14 02:02:39',
  lastModifiedBy: 'sysadmin',
  lastModifyTime: '2022-09-14 02:02:39',
  state: 1,
  fields: [
    text('code', '编码').required(),
    text('name', '名称').required(),
    select('type', '类型', { dict: 'xxxType' }),
    number('quantity', '数量', { precision: 2 }),
    date('startDate', '开始日期'),
    radio('status', '状态', { dict: 'xxxStatus' }),
    checkbox('tags', '标签', { dict: 'xxxTags' }),
    switchField('isActive', '是否启用'),
    textarea('remark', '备注'),
    upload('attachments', '附件'),
  ],
});
